name: offline_guardian
description: A 3-tier women's safety SOS application.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI and state
  provider: ^6.0.5
  
  # Core / Crypto
  encrypt: ^5.0.1
  pointycastle: ^3.7.3
  flutter_secure_storage: ^10.3.1
  uuid: ^4.1.0

  # Location and Hardware
  geolocator: ^14.0.3
  camera: ^0.12.0+2
  volume_controller: ^3.6.0

  # Tier 1 - Online
  socket_io_client: ^3.1.6
  connectivity_plus: ^7.3.1

  # Tier 2 - SMS
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
